version: '3.8'

services:
  # Base de datos MySQL
  mysql-db:
    image: mysql:8.0
    container_name: restaurante-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-restaurante123}
      MYSQL_DATABASE: ${DB_NAME:-restaurante_db}
      MYSQL_USER: ${DB_USER:-restaurante_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-restaurante_pass}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf:/etc/mysql/conf.d
    networks:
      - restaurante-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # Aplicación FastAPI
  fastapi-app:
    build: .
    container_name: restaurante-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${DB_USER:-restaurante_user}:${DB_PASSWORD:-restaurante_pass}@mysql-db:3306/${DB_NAME:-restaurante_db}
    networks:
      - restaurante-network
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  # Adminer para gestión de BD (opcional)
  adminer:
    image: adminer:latest
    container_name: restaurante-adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - restaurante-network
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local

networks:
  restaurante-network:
    driver: bridge
